### PR TITLE
module.ceylon: Update java-vertx module dependencies to use maven repo…

### PR DESCRIPTION
**Pull request by xkr47**
…instead of CMR

- no need to upload all java deps to CMR (Ceylon Herd)
- source jars available for end-users through maven repos

I understand that this probably affects the development environment somewhat but since the dependencies are in fact maven modules, just running "mvn install" on the vert-x3 projects should suffice..

### CODE REVIEW

**Comment by vietj** [comment]
doe it mean we could avoid to import these modules in Herd ?

**Comment by xkr47** [comment]
@vietj yes

**Comment by vietj** [comment]
it looks good to me as simplification of the build.

I avoided to use maven resolution in the past because I had lot of problems with it, one of them was due to the fact that the maven resolution in Ceylon was using a very old fork of Aether and when running in Maven, this was a total failure.

**Comment by xkr47** [comment]
Hope it works better now. If vertx uses any native jars, their operation may be worth verifying.

**Comment by quintesse** [comment]
@vietj at least @fromage did a *lot* of work on the Maven support for 1.3.1, so it probably works much better now. But it will have to be tested of course.

**Comment by vietj** [comment]
I am trying this on my machine and I get:

```
ERROR : Compilation error at (50,114) in /Users/julien/java/vertx-lang-ceylon/vertx-lang-ceylon/target/ceylon/main/io/vertx/ceylon/core/buffer/buffer_.java:Ceylon backend error: cannot access io.netty.buffer.ByteBuf
  class file for io.netty.buffer.ByteBuf not found
[ERROR] Compilation error at (50,114) in /Users/julien/java/vertx-lang-ceylon/vertx-lang-ceylon/target/ceylon/main/io/vertx/ceylon/core/buffer/buffer_.java:Ceylon backend error: cannot access io.netty.buffer.ByteBuf
  class file for io.netty.buffer.ByteBuf not found
```

**Comment by FroMage** [comment]
Did you declare a dependency to it? That error seems weird in any case.

**Comment by vietj** [comment]
@FroMage I expected the PR to work out of the box :-)

**Comment by xkr47** [comment]
Ok I'll see what I can do.

**Comment by xkr47** [comment]
Nope, doesn't work. Tried different combinations of the changes I made. I suggest we wait a few days for the "any day now" 1.3.1 release that @quintesse said would include great improvements. I guess it might be enough to just update the ceylon-maven-plugin if you otherwise want to retain 1.3.0 (or 1.2.x) compatibility?
